export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_MOVIE_LIST = 'FETCH_MOVIE_LIST';
export const FETCH_MOVIE_BY_ID = 'FETCH_MOVIE_BY_ID';
export const SET_INFINITE_BUSY = 'SET_INFINITE_BUSY';
export const CLEAN_MOVIES = 'CLEAN_MOVIES';
export const CLEAN_MOVIE_LIST = 'CLEAN_MOVIE_LIST';
export const CLEAN_MOVIE = 'CLEAN_MOVIE';
